GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/62ceddd65f01dcbaaf694494

###
POST http://localhost:3000/api/users/ HTTP/1.1
Content-Type: application/json

{
    "name" : "Lisa",
    "userName" : "LSimpson",
    "email" : "lisasimpson@gmail.com",
    "company":"62d604594a850d9416099870"
}
###
POST http://localhost:3000/api/companies/ HTTP/1.1
Content-Type: application/json

{
    "name":"FOX"
}

###
GET   http://localhost:3000/api/companies HTTP/1.1
Content-Type: application/json

{
    
}

###
DELETE http://localhost:3000/api/users/62cedd4d5f01dcbaaf694492

###
POST http://localhost:3000/api/example/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded

{"firstName" : "Lisa", "lastName" : "Simpson", "age" : 10}
